# Time Sync module properties
app.node.id=node1
server.port=8084

# NTP configuration
app.ntp.server=pool.ntp.org
app.ntp.sync-interval-ms=60000

# Peer nodes
app.peers=http://localhost:8085,http://localhost:8086

logging.level.com.payment.timesync=DEBUG
